apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector-pvc
  namespace: experimental
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: vsan-shared-datastore-immediate-storage-class